# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_discord import main_pb2 as grpc__discord_dot_main__pb2


class DiscordStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Check = channel.unary_unary(
        '/grpc_discord.Discord/Check',
        request_serializer=grpc__discord_dot_main__pb2.Ping.SerializeToString,
        response_deserializer=grpc__discord_dot_main__pb2.Pong.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/grpc_discord.Discord/GetUser',
        request_serializer=grpc__discord_dot_main__pb2.GetUserRequest.SerializeToString,
        response_deserializer=grpc__discord_dot_main__pb2.GetUserResponse.FromString,
        )


class DiscordServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Check(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiscordServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Check': grpc.unary_unary_rpc_method_handler(
          servicer.Check,
          request_deserializer=grpc__discord_dot_main__pb2.Ping.FromString,
          response_serializer=grpc__discord_dot_main__pb2.Pong.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=grpc__discord_dot_main__pb2.GetUserRequest.FromString,
          response_serializer=grpc__discord_dot_main__pb2.GetUserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc_discord.Discord', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
