# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: grpc_discord/main.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import grpc_discord.main_pb2


class DiscordBase(abc.ABC):

    @abc.abstractmethod
    async def Check(self, stream):
        pass

    @abc.abstractmethod
    async def GetUser(self, stream):
        pass

    def __mapping__(self):
        return {
            '/grpc_discord.Discord/Check': grpclib.const.Handler(
                self.Check,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc_discord.main_pb2.Ping,
                grpc_discord.main_pb2.Pong,
            ),
            '/grpc_discord.Discord/GetUser': grpclib.const.Handler(
                self.GetUser,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc_discord.main_pb2.GetUserRequest,
                grpc_discord.main_pb2.GetUserResponse,
            ),
        }


class DiscordStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Check = grpclib.client.UnaryUnaryMethod(
            channel,
            '/grpc_discord.Discord/Check',
            grpc_discord.main_pb2.Ping,
            grpc_discord.main_pb2.Pong,
        )
        self.GetUser = grpclib.client.UnaryUnaryMethod(
            channel,
            '/grpc_discord.Discord/GetUser',
            grpc_discord.main_pb2.GetUserRequest,
            grpc_discord.main_pb2.GetUserResponse,
        )
